# slf4j日志配置
logging:
  #  config: classpath:/logback.xml
  # 配置级别
  level:
    root: info

#spring:
#  datasource:
#    driverClassName:  org.mariadb.jdbc.Driver
#    url: "jdbc:mariadb://cloud.miaokeli.vip:3306/internal_voice_db"
#    username: "admin"
#    password: "rG7*3lbOlY"
#    testOnBorrow: true
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: SELECT 1
#    max-active: 15
#    max-idle: 10
#    max-wait: 8000

mybatis:
  config-location: classpath:mybatis-config.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis 分页插件 pageHelper 配置
pagehelper:
  #支持通过 Mapper 接口参数来传递分页参数，为 true 时，分页插件会从查询方法的参数值中查找 pageNum、pageSize 参数的值进行自动分页。默认值 false.
  supportMethodsArguments: true
  #分页合理化参数，为 true 时，pageNum<=0 会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0, 就会查询出全部的结果(相当于没有执行分页查询，但是返回结果仍然是 Page 类型),默认值为 false，
  pageSizeZero: true

crud:
  logicalDeletion: true

  #URL	jdbc:mariadb://cloud.miaokeli.vip:3306/internal_voice_db